// <auto-generated />
using AlHidayahPro.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlHidayahPro.Data.Migrations
{
    [DbContext(typeof(IslamicDbContext))]
    [Migration("20251109205323_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("AlHidayahPro.Data.Models.AudioRecitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AudioUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AyahNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RecitationStyle")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReciterName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SurahNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReciterName", "SurahNumber", "AyahNumber");

                    b.ToTable("AudioRecitations");
                });

            modelBuilder.Entity("AlHidayahPro.Data.Models.Hadith", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArabicText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Book")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BookNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Chapter")
                        .HasColumnType("TEXT");

                    b.Property<string>("Collection")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HadithNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Narrator")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Collection", "HadithNumber");

                    b.ToTable("Hadiths");
                });

            modelBuilder.Entity("AlHidayahPro.Data.Models.QuranVerse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArabicText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("AyahNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnglishTranslation")
                        .HasColumnType("TEXT");

                    b.Property<int>("JuzNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SurahNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Transliteration")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SurahNumber", "AyahNumber")
                        .IsUnique();

                    b.ToTable("QuranVerses");
                });

            modelBuilder.Entity("AlHidayahPro.Data.Models.Surah", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishTranslation")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumberOfAyahs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RevelationType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("Surahs");
                });

            modelBuilder.Entity("AlHidayahPro.Data.Models.QuranVerse", b =>
                {
                    b.HasOne("AlHidayahPro.Data.Models.Surah", "Surah")
                        .WithMany("Verses")
                        .HasForeignKey("SurahNumber")
                        .HasPrincipalKey("Number")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Surah");
                });

            modelBuilder.Entity("AlHidayahPro.Data.Models.Surah", b =>
                {
                    b.Navigation("Verses");
                });
#pragma warning restore 612, 618
        }
    }
}
